service: tara

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  timeout: 60

functions:
  master:
    handler: index.handler
    layers:
      - ${cf:selenium-layer-dev.SeleniumLayerExport}
      - ${cf:selenium-layer-dev.ChromedriverLayerExport}